#################################################
# Corporate legal boilerplate                   #
# goes in here                                  #
#################################################

- name: Download the Source
  get_url:
    url: "{{ confluence_download_link }}/{{ confluence_software_file }}"
    dest: "/tmp/{{ confluence_software_file }}"

- name: Create the installation directory
  file:
    path: "{{ confluence_path }}/"
    state: directory
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group}}"
    mode: '0744'

- name: Unarchive the confluence software to the installation directory
  unarchive:
    src: "/tmp/{{ confluence_software_file }}"
    dest: "{{ confluence_path }}/"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group}}"
    remote_src: yes

- name: Ensure the ownership of the unarchived files are correct
  file:
    path: "{{ confluence_path }}/"
    state: directory
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group}}"
    mode: '0777'
    recurse: yes

- name: Create the home directory
  file:
    path: "{{ confluence_software_home }}"
    state: directory
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group}}"
    mode: '0777'

- name: Set the environment variable for confluence
  lineinfile:
    state: present
    dest: /etc/profile
    regexp: "export confluence_HOME=.*"
    line: "export confluence_HOME={{ confluence_software_home }}"

- name: Edit the confluence application properties file
  lineinfile:
    state: present
    dest: "{{ confluence_path}}/{{confluence_software_folder}}/confluence/WEB-INF/classes/confluence-init.properties"
    regexp: "confluence.home=.*"
    line: "confluence.home={{ confluence_software_home }}"
