- name:  Install the terraform prerequiste packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - gnupg
    - software-properties-common
    - curl

- name: Install terraform gpg key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present

- name: Work out the distribution
  command: lsb_release -sc
  register: dist_query

- name: Add terraform repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ dist_query.stdout }} main"
    state: present
    update_cache: yes

- name: Install terraform
  apt:
    name: terraform
    state: latest
